# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Vitality-Athena-Ai

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://45d89fdb4c734bf28fd7f2d65b272e1c.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_308dca0e00014caca8408a2f3b6795c3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c03f148ff40c47c6b4cd791989a31ed0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: 45d89fdb4c734bf28fd7f2d65b272e1c.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_308dca0e00014caca8408a2f3b6795c3 }}/vitality-athena-ai:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Vitality-Athena-Ai'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b60696e9a7864de5afa7534cfc3f0c33 }}
        images: '45d89fdb4c734bf28fd7f2d65b272e1c.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_308dca0e00014caca8408a2f3b6795c3 }}/vitality-athena-ai:${{ github.sha }}'